export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  CPF_ALREADY_EXISTS = 'CPF_ALREADY_EXISTS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',

  // Pix
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  PIX_KEY_NOT_FOUND = 'PIX_KEY_NOT_FOUND',
  PIX_KEY_ALREADY_EXISTS = 'PIX_KEY_ALREADY_EXISTS',
  PIX_KEY_LIMIT_REACHED = 'PIX_KEY_LIMIT_REACHED',
  PIX_DAILY_LIMIT_EXCEEDED = 'PIX_DAILY_LIMIT_EXCEEDED',
  PIX_NIGHT_LIMIT_EXCEEDED = 'PIX_NIGHT_LIMIT_EXCEEDED',
  PIX_RATE_LIMIT_EXCEEDED = 'PIX_RATE_LIMIT_EXCEEDED',
  SELF_TRANSFER_NOT_ALLOWED = 'SELF_TRANSFER_NOT_ALLOWED',

  // Cards
  CARD_NOT_FOUND = 'CARD_NOT_FOUND',
  CARD_ALREADY_BLOCKED = 'CARD_ALREADY_BLOCKED',
  CARD_ALREADY_ACTIVE = 'CARD_ALREADY_ACTIVE',

  // Payments
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  // General
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DUPLICATE_REQUEST = 'DUPLICATE_REQUEST',
}

export const ERROR_STATUS_MAP: Record<ErrorCode, number> = {
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.EMAIL_ALREADY_EXISTS]: 409,
  [ErrorCode.CPF_ALREADY_EXISTS]: 409,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.TOKEN_EXPIRED]: 401,
  [ErrorCode.INSUFFICIENT_BALANCE]: 422,
  [ErrorCode.PIX_KEY_NOT_FOUND]: 404,
  [ErrorCode.PIX_KEY_ALREADY_EXISTS]: 409,
  [ErrorCode.PIX_KEY_LIMIT_REACHED]: 422,
  [ErrorCode.PIX_DAILY_LIMIT_EXCEEDED]: 422,
  [ErrorCode.PIX_NIGHT_LIMIT_EXCEEDED]: 422,
  [ErrorCode.PIX_RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.SELF_TRANSFER_NOT_ALLOWED]: 422,
  [ErrorCode.CARD_NOT_FOUND]: 404,
  [ErrorCode.CARD_ALREADY_BLOCKED]: 422,
  [ErrorCode.CARD_ALREADY_ACTIVE]: 422,
  [ErrorCode.PAYMENT_FAILED]: 422,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.DUPLICATE_REQUEST]: 409,
}
